version: '3.9'
services:
  python:
    image: robertshand/python-hello-world
    networks:
      dnsserver:
        ipv4_address: 172.100.30.10 # hello world static ip

  python2:
    image: robertshand/python-hello-world
    networks:
      dnsserver:
        ipv4_address: 172.100.30.58 # hello world static ip

  dns:
    image: registry.gitlab.com/maissacrement/dns
    domainname: myst.yana
    network_mode: host
    hostname: dns
    ipc: host
    privileged: true
    environment:
      IP: '172.100.30.1' # ip of dns server
      CIDR: '172.100.30.0/24' # ip address auth range
      DNS_BASE: 'myst.yana' # dns server base name
      DNS1: 'www:172.100.30.10' # [subdomain]:[targetedIp]
      DNS2: 'reduncy:172.100.30.58' # [subdomain]:[targetedIp]
    extra_hosts:
      - "www.myst.yana:172.100.30.10"
      - "reduncy.myst.yana:172.100.30.58"

networks:
  dnsserver:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.30.0/24
          gateway: 172.100.30.1