version: '3.9'
services:
  python:
    image: robertshand/python-hello-world
    networks:
      dnsserver:
         ipv4_address: 172.100.30.10 # hello world static ip
    ports:
      - 7777:80

  dns:
    image: registry.gitlab.com/maissacrement/dns
    domainname: example.com
    hostname: dns
    ipc: host
    privileged: true
    volumes:
      - ./nginx/example.conf:/usr/local/nginx/conf/includes/example.conf
    networks:
      dnsserver:
        ipv4_address: 172.100.30.2 # ip dns server
    environment:
      IP: '172.100.30.2' # ip dns server
      CIDR: '172.100.30.0/24' # ip address auth range
      DNS_BASE: 'example.com' # dns server base name
      DNS1: 'www:172.100.30.1' # [subdomain]:[targetedIp]

networks:
  dnsserver:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.30.0/24
          gateway: 172.100.30.1