version: '3.9'
services:
  python:
    image: robertshand/python-hello-world
    networks:
      dnsserver:
         ipv4_address: 172.100.30.10 # hello world static ip

  dns:
    image: registry.gitlab.com/maissacrement/dns
    domainname: myst.yana
    hostname: dns
    ipc: host
    privileged: true
    volumes:
      - ./nginx/example.conf:/usr/local/nginx/conf/includes/example.conf
    networks:
      dnsserver:
        ipv4_address: 172.100.30.2 # ip dns server
    environment:
      IP: '172.100.30.2' # ip dns server
      CIDR: '172.100.30.0/24' # ip address auth range
      DNS_BASE: 'myst.yana' # dns server base name
      DNS1: 'base:172.100.30.10' # [subdomain]:[targetedIp]
    extra_hosts:
      - "base.myst.yana:172.100.30.2"

networks:
  dnsserver:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.30.0/24
          gateway: 172.100.30.1